# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 14:14
from __future__ import unicode_literals

import attachment.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('attachment', '0002_auto_20160829_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file_list', models.TextField(blank=True, null=True, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0444\u0430\u0439\u043b\u043e\u0432')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043d')),
                ('unpacked', models.BooleanField(default=False, verbose_name='\u0420\u0430\u0441\u043f\u0430\u043a\u043e\u0432\u0430\u043d')),
                ('zip_file', models.FileField(help_text='\u0412\u043d\u0438\u043c\u0430\u043d\u0438\u0435: \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0438 \u0440\u0430\u0441\u043f\u0430\u043a\u043e\u0432\u043a\u0430 \u0430\u0440\u0445\u0438\u0432\u0430 \u043c\u043e\u0436\u0435\u0442 \u0437\u0430\u043d\u044f\u0442\u044c \u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f', upload_to=b'upload/attachment/source', verbose_name='ZIP-\u0430\u0440\u0445\u0438\u0432')),
                ('use_filenames_as_titles', models.BooleanField(default=False, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0438\u043c\u0435\u043d\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0432 \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0435 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u0432')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u0410\u0440\u0445\u0438\u0432 \u0432\u043b\u043e\u0436\u0435\u043d\u0438\u0439',
                'verbose_name_plural': '\u0410\u0440\u0445\u0438\u0432\u044b \u0432\u043b\u043e\u0436\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.AlterField(
            model_name='attachmentfile',
            name='file',
            field=models.FileField(upload_to=b'upload/attachment/source', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachmentimage',
            name='image',
            field=attachment.fields.ImagePreviewField(upload_to=b'upload/attachment/source', verbose_name='image'),
        ),
    ]
